name: Terraform Auto Format

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"

permissions:
  contents: write

jobs:
  terraform-fmt:
    name: Auto Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Format Terraform Code
        run: terraform fmt -recursive -list=true -write=true

      - name: Show Git Status
        run: git status

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and Push Changes
        run: |
          git add -u
          git diff --cached --quiet || git commit -m "Auto-format Terraform files"
          git push
