name: Terraform Format Check

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"

jobs:
  terraform-fmt:
    name: Check Terraform Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Run terraform fmt
        run: terraform fmt -recursive
