name: Terraform Format Check

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tf"

jobs:
  terraform-fmt:
    name: Check Terraform Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Run terraform fmt
        run: terraform fmt --recursive

      - name: Verify Formatting (ignore whitespace-only changes)
        id: verify_fmt
        run: |
          if [[ -n $(git diff --ignore-all-space --name-only) ]]; then
            echo "✖ Files have non-whitespace uncommitted changes after formatting."
            echo "💡 Please review and commit the necessary changes."
            echo "format_status=not_formatted" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "✓ No non-whitespace uncommitted changes after formatting."
            echo "format_status=formatted" >> $GITHUB_OUTPUT
          fi

      - name: Output Formatting Result
        run: |
          echo "Terraform format check result: ${{ steps.verify_fmt.outputs.format_status }}"
